module Quone.Generate.R
  ( generate
  ) where

import qualified Data.Map.Strict as Map
import Data.List (intercalate)

import Quone.AST.Source
import Quone.Type.Type
import Quone.Type.Infer (InferState(..))

data Codegen = Codegen
  { cgConstructors :: Map.Map String CtorInfo
  , cgTmpCounter   :: !Int
  , cgAliasMap     :: [(String, [(String, Ty)])]
  }

data CtorInfo = CtorInfo
  { _ciTypeName :: String
  , ciArity     :: Int
  }

newCodegen :: Program -> InferState -> Codegen
newCodegen prog inferSt =
  let ctors = Map.fromList
        [ (variantName v, CtorInfo (typeName td) (length (variantFields v)))
        | DeclType td <- progDecls prog
        , v <- typeVariants td
        ]
      aliases = buildAliasMap inferSt
  in Codegen ctors 0 aliases

buildAliasMap :: InferState -> [(String, [(String, Ty)])]
buildAliasMap _inferSt = []

hasTypeDecls :: Program -> Bool
hasTypeDecls prog = any isTypeDecl (progDecls prog)
  where isTypeDecl (DeclType _) = True
        isTypeDecl _ = False

isExported :: Program -> String -> Bool
isExported prog name = case progModule prog of
  Nothing -> False
  Just m -> case moduleExports m of
    ExportAll     -> True
    ExportList ns -> name `elem` ns

generate :: Program -> [(String, Ty)] -> InferState -> String
generate prog types inferSt =
  let cg0 = newCodegen prog inferSt
      typeMap = Map.fromList types
  in runGen cg0 prog typeMap

runGen :: Codegen -> Program -> Map.Map String Ty -> String
runGen cg0 prog typeMap =
  let header = "# Generated by quone\n\n"
      libs = concatMap genLibrary (progDecls prog)
      libSep = if any isLib (progDecls prog) then "\n" else ""
      variant = if hasTypeDecls prog
                then makeVariant ++ "\n" ++ concatMap (genTypeDecl cg0) (progDecls prog)
                else ""
      aliases = concatMap (genTypeAliasDecl cg0) (progDecls prog)
      (defs, _) = foldl (\(acc, cg) d -> case d of
        DeclLet ld ->
          let roxy = case Map.lookup (letName ld) typeMap of
                Just ty -> genRoxygen ld ty (cgAliasMap cg)
                Nothing -> ""
              export = if isExported prog (letName ld) then "#' @export\n" else ""
              (code, cg') = genLetDecl cg ld
          in (acc ++ roxy ++ export ++ code ++ "\n", cg')
        _ -> (acc, cg)
        ) ("", cg0) (progDecls prog)
  in header ++ libs ++ libSep ++ variant ++ aliases ++ defs
  where
    isLib (DeclLibrary _) = True
    isLib _ = False

genLibrary :: Decl -> String
genLibrary (DeclLibrary name) = "library(" ++ name ++ ")\n"
genLibrary _ = ""

genTypeDecl :: Codegen -> Decl -> String
genTypeDecl cg (DeclType td) = concatMap (genConstructor cg (typeName td)) (typeVariants td)
genTypeDecl _ _ = ""

genConstructor :: Codegen -> String -> VariantDecl -> String
genConstructor _ typN v
  | null (variantFields v) =
    variantName v ++ " <- function() {\n  .make_variant('" ++ typN ++ "', '" ++ variantName v ++ "')\n}\n\n"
  | otherwise =
    let n = length (variantFields v)
        params = map (\i -> "field" ++ show i) [1..n]
        paramsStr = intercalate ", " params
        fieldsStr = intercalate ", " (map (\p -> p ++ " = " ++ p) params)
    in variantName v ++ " <- function(" ++ paramsStr ++ ") {\n  .make_variant('" ++ typN ++ "', '" ++ variantName v ++ "', list(" ++ fieldsStr ++ "))\n}\n\n"

genTypeAliasDecl :: Codegen -> Decl -> String
genTypeAliasDecl _cg (DeclTypeAlias ta) =
  let isDF = any isDFType (aliasBody ta)
      (kind, fieldWord) = if isDF then ("dataframe", "columns") else ("record", "fields")
  in "#' " ++ aliasName ta ++ "\n#'\n#' A " ++ kind ++ " with " ++ fieldWord ++ "\n" ++ aliasName ta ++ " <- NULL\n\n"
  where
    isDFType (TEDataframe _) = True
    isDFType _ = False
genTypeAliasDecl _ _ = ""

genRoxygen :: LetDecl -> Ty -> [(String, [(String, Ty)])] -> String
genRoxygen ld ty aliases =
  let (names, _) = assignVarNames ty Map.empty 0
  in case (letExpr ld, ty) of
    (ELambda params _, TyFunc paramTys retTy) ->
      let paramLines = zipWith (\name pty ->
            "#' @param " ++ name ++ " [" ++ formatTyWith names aliases pty ++ "]"
            ) params paramTys
          retLine = "#' @return [" ++ formatTyWith names aliases retTy ++ "]"
      in unlines (paramLines ++ [retLine])
    _ -> "#' @type [" ++ formatTyWith names aliases ty ++ "]\n"

genLetDecl :: Codegen -> LetDecl -> (String, Codegen)
genLetDecl cg ld = case letExpr ld of
  ELambda params body ->
    let (bodyStr, cg') = genBody cg body
    in (letName ld ++ " <- function(" ++ intercalate ", " params ++ ") {\n" ++ indentLines 2 bodyStr ++ "\n}\n", cg')
  _ ->
    let (exprStr, cg') = genExpr cg (letExpr ld)
    in (letName ld ++ " <- " ++ exprStr ++ "\n", cg')

genBody :: Codegen -> Expr -> (String, Codegen)
genBody cg expr = case expr of
  ELet bindings body ->
    let (bindLines, cg1) = foldl (\(acc, cg') (name, e) ->
          if name == "_"
          then let (es, cg'') = genExpr cg' e in (acc ++ [es], cg'')
          else case splitDotted name of
            Just (obj, field) ->
              let (es, cg'') = genExpr cg' e
              in (acc ++ [obj ++ "$" ++ field ++ " <- " ++ es], cg'')
            Nothing -> case e of
              ELambda params lbody ->
                let (bs, cg'') = genBody cg' lbody
                in (acc ++ [name ++ " <- function(" ++ intercalate ", " params ++ ") {\n" ++ indentLines 2 bs ++ "\n}"], cg'')
              _ ->
                let (es, cg'') = genExpr cg' e
                in (acc ++ [name ++ " <- " ++ es], cg'')
          ) ([], cg) bindings
        (bodyStr, cg2) = genBody cg1 body
    in (unlines bindLines ++ bodyStr, cg2)
  _ -> genExpr cg expr

splitDotted :: String -> Maybe (String, String)
splitDotted s = case break (== '.') s of
  (_, [])    -> Nothing
  (a, _:b)   -> Just (a, b)

genExpr :: Codegen -> Expr -> (String, Codegen)
genExpr cg expr = case expr of
  EVar name ->
    case Map.lookup name (cgConstructors cg) of
      Just info | ciArity info == 0 -> (name ++ "()", cg)
      _ -> (name, cg)

  EInt n -> (show n ++ "L", cg)

  EFloat f ->
    let s = show f
    in (if '.' `elem` s then s else s ++ ".0", cg)

  EBool b -> (if b then "TRUE" else "FALSE", cg)

  EStr s ->
    let escaped = concatMap escChar s
    in ("\"" ++ escaped ++ "\"", cg)

  EVecLit elems ->
    let (parts, cg') = mapAccumCg cg elems genExpr
    in ("c(" ++ intercalate ", " parts ++ ")", cg')

  ELambda params body ->
    let (bodyStr, cg') = genBody cg body
    in ("function(" ++ intercalate ", " params ++ ") {\n" ++ indentLines 2 bodyStr ++ "\n}", cg')

  EUnit -> ("", cg)

  ECall func args ->
    case func of
      EVar name | Just code <- genBuiltinCall cg name args -> code
      _ ->
        let realArgs = filter (not . isUnitExpr) args
            (argStrs, cg1) = mapAccumCg cg realArgs genExpr
            (funcStr, cg2) = case func of
              EVar name -> (name, cg1)
              _         -> genExpr cg1 func
        in (funcStr ++ "(" ++ intercalate ", " argStrs ++ ")", cg2)

  EIf cond thenE elseE ->
    let (c, cg1) = genExpr cg cond
        (t, cg2) = genExpr cg1 thenE
        (e, cg3) = genExpr cg2 elseE
    in ("if (" ++ c ++ ") {\n" ++ indentLines 2 t ++ "\n} else {\n" ++ indentLines 2 e ++ "\n}", cg3)

  EMatch scrutinee arms -> genMatch cg scrutinee arms

  EBinary op left right ->
    let prec = binOpPrecedence op
        (l, cg1) = genExpr cg left
        lStr = case left of
          EBinary lop _ _ | binOpPrecedence lop < prec -> "(" ++ l ++ ")"
          _ -> l
        (r, cg2) = genExpr cg1 right
        rStr = case right of
          EBinary rop _ _ | binOpPrecedence rop <= prec -> "(" ++ r ++ ")"
          _ -> r
    in (lStr ++ " " ++ binOpSymbol op ++ " " ++ rStr, cg2)

  ELet bindings body ->
    let (bindParts, cg1) = foldl (\(acc, cg') (name, e) -> case e of
          ELambda params lbody ->
            let (bs, cg'') = genBody cg' lbody
            in (acc ++ [name ++ " <- function(" ++ intercalate ", " params ++ ") {\n" ++ indentLines 2 bs ++ "\n}"], cg'')
          _ ->
            let (es, cg'') = genExpr cg' e
            in (acc ++ [name ++ " <- " ++ es], cg'')
          ) ([], cg) bindings
        (bodyStr, cg2) = genBody cg1 body
        inner = unlines bindParts ++ bodyStr
    in ("local({\n" ++ indentLines 2 inner ++ "\n})", cg2)

  ERecord fields ->
    let (parts, cg') = mapAccumCg cg fields (\cg'' (n, e) -> let (es, cg''') = genExpr cg'' e in (n ++ " = " ++ es, cg'''))
    in ("list(" ++ intercalate ", " parts ++ ")", cg')

  EDataFrame fields ->
    let (parts, cg') = mapAccumCg cg fields (\cg'' (n, e) -> let (es, cg''') = genExpr cg'' e in (n ++ " = " ++ es, cg'''))
    in ("data.frame(" ++ intercalate ", " parts ++ ")", cg')

  EFieldAccess e field ->
    let (es, cg') = genExpr cg e
    in (es ++ "$" ++ field, cg')

  EDplyr verb args ->
    let (parts, cg') = mapAccumCg cg args (\cg'' a -> case a of
          DplyrColumn name -> (name, cg'')
          DplyrPred pred'  -> let (es, cg''') = genColExpr cg'' pred' in (es, cg''')
          DplyrNamed name pred' -> let (es, cg''') = genColExpr cg'' pred' in (name ++ " = " ++ es, cg'''))
    in ("dplyr::" ++ verb ++ "(" ++ intercalate ", " parts ++ ")", cg')

  EPipe _ _ ->
    let (steps, base) = collectPipeSteps expr
        (first, cg1) = genExpr cg base
        needsP = needsPipeParens base
        firstStr = if needsP then "(" ++ first ++ ")" else first
        (result, cg2) = foldl (\(acc, cg') step ->
          let (rhs, cg'') = genPipeRhs cg' step
          in (acc ++ " |>\n  " ++ rhs, cg'')
          ) (firstStr, cg1) steps
    in (result, cg2)

collectPipeSteps :: Expr -> ([Expr], Expr)
collectPipeSteps (EPipe left right) =
  let (steps, base) = collectPipeSteps left
  in (steps ++ [right], base)
collectPipeSteps e = ([], e)

needsPipeParens :: Expr -> Bool
needsPipeParens (EBinary{}) = True
needsPipeParens (ECall (EVar name) args)
  | name == "map" && length args == 2 = isVecBody args
  | name == "map2" && length args == 3 = isVecBody args
  | otherwise = False
  where
    isVecBody (ELambda params body : _) = length params <= 2 && isVectorizableBody body
    isVecBody _ = False
needsPipeParens _ = False

genPipeRhs :: Codegen -> Expr -> (String, Codegen)
genPipeRhs cg expr = case expr of
  EDplyr{} -> genExpr cg expr
  EVar name ->
    let rName = builtinRName name
    in (rName ++ "()", cg)
  ECall (EVar name) args
    | Just (code, cg') <- genBuiltinPipeRhs cg name args -> (code, cg')
  ECall func args ->
    let (argStrs, cg1) = mapAccumCg cg args genExpr
        (funcStr, cg2) = case func of
          EVar name -> (name, cg1)
          _         -> genExpr cg1 func
    in (funcStr ++ "(" ++ intercalate ", " argStrs ++ ")", cg2)
  _ ->
    let (code, cg') = genExpr cg expr
    in ("(" ++ code ++ ")", cg')

genBuiltinCall :: Codegen -> String -> [Expr] -> Maybe (String, Codegen)
genBuiltinCall cg name args = case (name, args) of
  ("map", [ELambda [p] body, xs]) | isVectorizableBody body ->
    let (xsStr, cg1) = genExpr cg xs
        subs = Map.singleton p xsStr
        (result, cg2) = genVectorized cg1 body subs
    in Just (result, cg2)
  ("map", [f, xs]) ->
    let (fStr, cg1) = genExpr cg f
        (xsStr, cg2) = genExpr cg1 xs
    in Just ("purrr::map_dbl(" ++ xsStr ++ ", " ++ fStr ++ ")", cg2)
  ("map2", [ELambda [p1, p2] body, xs, ys]) | isVectorizableBody body ->
    let (xsStr, cg1) = genExpr cg xs
        (ysStr, cg2) = genExpr cg1 ys
        subs = Map.fromList [(p1, xsStr), (p2, ysStr)]
        (result, cg3) = genVectorized cg2 body subs
    in Just (result, cg3)
  ("map2", [f, xs, ys]) ->
    let (fStr, cg1) = genExpr cg f
        (xsStr, cg2) = genExpr cg1 xs
        (ysStr, cg3) = genExpr cg2 ys
    in Just ("purrr::map2_dbl(" ++ xsStr ++ ", " ++ ysStr ++ ", " ++ fStr ++ ")", cg3)
  ("reduce", [f, ini, xs]) ->
    let (fStr, cg1) = genExpr cg f
        (iniStr, cg2) = genExpr cg1 ini
        (xsStr, cg3) = genExpr cg2 xs
    in Just ("purrr::reduce(" ++ xsStr ++ ", " ++ fStr ++ ", .init = " ++ iniStr ++ ")", cg3)
  ("keep", [f, xs]) ->
    let (fStr, cg1) = genExpr cg f
        (xsStr, cg2) = genExpr cg1 xs
    in Just ("purrr::keep(" ++ xsStr ++ ", " ++ fStr ++ ")", cg2)
  ("discard", [f, xs]) ->
    let (fStr, cg1) = genExpr cg f
        (xsStr, cg2) = genExpr cg1 xs
    in Just ("purrr::discard(" ++ xsStr ++ ", " ++ fStr ++ ")", cg2)
  ("to_double", [x]) ->
    let (xStr, cg1) = genExpr cg x
    in Just ("as.numeric(" ++ xStr ++ ")", cg1)
  _ -> Nothing

genBuiltinPipeRhs :: Codegen -> String -> [Expr] -> Maybe (String, Codegen)
genBuiltinPipeRhs cg name args = case (name, args) of
  ("map", [ELambda [p] body]) | isVectorizableBody body ->
    let subs = Map.singleton p ".x"
        (result, cg1) = genVectorized cg body subs
    in Just ("(\\(.x) " ++ result ++ ")()", cg1)
  ("map", [f]) ->
    let (fStr, cg1) = genExpr cg f
    in Just ("purrr::map_dbl(" ++ fStr ++ ")", cg1)
  ("map2", [ELambda [p1, p2] body, ys]) | isVectorizableBody body ->
    let (ysStr, cg1) = genExpr cg ys
        subs = Map.fromList [(p1, ".x"), (p2, ysStr)]
        (result, cg2) = genVectorized cg1 body subs
    in Just ("(\\(.x) " ++ result ++ ")()", cg2)
  ("map2", [f, ys]) ->
    let (fStr, cg1) = genExpr cg f
        (ysStr, cg2) = genExpr cg1 ys
    in Just ("purrr::map2_dbl(" ++ ysStr ++ ", " ++ fStr ++ ")", cg2)
  ("reduce", [f, ini]) ->
    let (fStr, cg1) = genExpr cg f
        (iniStr, cg2) = genExpr cg1 ini
    in Just ("purrr::reduce(" ++ fStr ++ ", .init = " ++ iniStr ++ ")", cg2)
  ("keep", [f]) ->
    let (fStr, cg1) = genExpr cg f
    in Just ("purrr::keep(" ++ fStr ++ ")", cg1)
  ("discard", [f]) ->
    let (fStr, cg1) = genExpr cg f
    in Just ("purrr::discard(" ++ fStr ++ ")", cg1)
  _ -> Nothing

isVectorizableBody :: Expr -> Bool
isVectorizableBody expr = case expr of
  EVar{}   -> True
  EInt{}   -> True
  EFloat{} -> True
  EBool{}  -> True
  EBinary _ l r -> isVectorizableBody l && isVectorizableBody r
  ECall (EVar name) [arg] -> name `elem` ["sqrt", "abs", "log", "exp"] && isVectorizableBody arg
  _ -> False

genVectorized :: Codegen -> Expr -> Map.Map String String -> (String, Codegen)
genVectorized cg body subs = case body of
  EVar name -> (Map.findWithDefault name name subs, cg)
  EInt n    -> (show n ++ "L", cg)
  EFloat f  -> let s = show f in (if '.' `elem` s then s else s ++ ".0", cg)
  EBool b   -> (if b then "TRUE" else "FALSE", cg)
  EBinary op l r ->
    let prec = binOpPrecedence op
        (lStr, cg1) = genVectorized cg l subs
        lFinal = case l of
          EBinary lop _ _ | binOpPrecedence lop < prec -> "(" ++ lStr ++ ")"
          _ -> lStr
        (rStr, cg2) = genVectorized cg1 r subs
        rFinal = case r of
          EBinary rop _ _ | binOpPrecedence rop <= prec -> "(" ++ rStr ++ ")"
          _ -> rStr
    in (lFinal ++ " " ++ binOpSymbol op ++ " " ++ rFinal, cg2)
  ECall (EVar name) [arg] ->
    let rName = builtinRName name
        (argStr, cg1) = genVectorized cg arg subs
    in (rName ++ "(" ++ argStr ++ ")", cg1)
  _ -> genExpr cg body

builtinRName :: String -> String
builtinRName name = case name of
  "to_double" -> "as.numeric"
  "map"       -> "purrr::map_dbl"
  "map2"      -> "purrr::map2_dbl"
  "reduce"    -> "purrr::reduce"
  "keep"      -> "purrr::keep"
  "discard"   -> "purrr::discard"
  _           -> name

genColExpr :: Codegen -> Expr -> (String, Codegen)
genColExpr cg expr = case expr of
  EVar name  -> (name, cg)
  EInt n     -> (show n, cg)
  EFloat f   -> let s = show f in (if '.' `elem` s then s else s ++ ".0", cg)
  EBool b    -> (if b then "TRUE" else "FALSE", cg)
  EStr s     -> ("\"" ++ s ++ "\"", cg)
  EBinary op l r ->
    let (lStr, cg1) = genColExpr cg l
        (rStr, cg2) = genColExpr cg1 r
    in (lStr ++ " " ++ binOpSymbol op ++ " " ++ rStr, cg2)
  ECall func args ->
    let (fStr, cg1) = genColExpr cg func
        realArgs = filter (not . isUnitExpr) args
        (argStrs, cg2) = mapAccumCg cg1 realArgs genColExpr
    in (fStr ++ "(" ++ intercalate ", " argStrs ++ ")", cg2)
  _ -> genExpr cg expr

genMatch :: Codegen -> Expr -> [(Pattern, Expr)] -> (String, Codegen)
genMatch cg0 scrutinee arms =
  let tmp = ".tmp_" ++ show (cgTmpCounter cg0)
      cg1 = cg0 { cgTmpCounter = cgTmpCounter cg0 + 1 }
      (scrutStr, cg2) = genExpr cg1 scrutinee
      inner0 = tmp ++ " <- " ++ scrutStr ++ "\n"
      (compiled, cg3) = foldl (\(acc, cg') (pat, body) ->
        let (conds, binds) = compilePattern pat tmp
            (bodyStr, cg'') = genExpr cg' body
        in (acc ++ [(conds, binds, bodyStr)], cg'')
        ) ([], cg2) arms
      (innerCode, _closed) = buildMatchCode compiled True False
  in ("local({\n" ++ indentLines 2 (inner0 ++ innerCode) ++ "\n})", cg3 { cgTmpCounter = cgTmpCounter cg3 })

buildMatchCode :: [([String], [(String, String)], String)] -> Bool -> Bool -> (String, Bool)
buildMatchCode [] _ closed = ("", closed)
buildMatchCode ((conds, binds, bodyStr):rest) first closed
  | null conds =
    if first
    then let bindLines = concatMap (\(n, p) -> n ++ " <- " ++ p ++ "\n") binds
         in (bindLines ++ bodyStr, True)
    else let bindLines = concatMap (\(n, p) -> "  " ++ n ++ " <- " ++ p ++ "\n") binds
         in ("} else {\n" ++ bindLines ++ indentLines 2 bodyStr ++ "\n}", True)
  | otherwise =
    let cond = intercalate " && " conds
        bindLines = concatMap (\(n, p) -> "  " ++ n ++ " <- " ++ p ++ "\n") binds
        header = if first
                 then "if (" ++ cond ++ ") {\n"
                 else "} else if (" ++ cond ++ ") {\n"
        armCode = header ++ bindLines ++ indentLines 2 bodyStr ++ "\n"
        (restCode, closed') = buildMatchCode rest False closed
    in if null rest && not closed'
       then (armCode ++ "} else {\n  stop('Non-exhaustive match')\n}", True)
       else (armCode ++ restCode, closed')

compilePattern :: Pattern -> String -> ([String], [(String, String)])
compilePattern pat path = case pat of
  PWildcard -> ([], [])
  PVar name -> ([], [(name, path)])
  PInt n    -> (["identical(" ++ path ++ ", " ++ show n ++ "L)"], [])
  PBool b   -> (["identical(" ++ path ++ ", " ++ (if b then "TRUE" else "FALSE") ++ ")"], [])
  PConstructor name pats ->
    let tagCond = "identical(" ++ path ++ "$`__tag__`, '" ++ name ++ "')"
        (subConds, subBinds) = unzip
          [ compilePattern p (path ++ "$field" ++ show (i :: Int))
          | (i, p) <- zip [1..] pats
          ]
    in (tagCond : concat subConds, concat subBinds)

isUnitExpr :: Expr -> Bool
isUnitExpr EUnit = True
isUnitExpr _     = False

escChar :: Char -> String
escChar '\\' = "\\\\"
escChar '"'  = "\\\""
escChar '\n' = "\\n"
escChar '\t' = "\\t"
escChar c    = [c]

indentLines :: Int -> String -> String
indentLines n s =
  let pad = replicate n ' '
  in unlines [if null line then "" else pad ++ line | line <- lines s]

mapAccumCg :: Codegen -> [a] -> (Codegen -> a -> (b, Codegen)) -> ([b], Codegen)
mapAccumCg cg [] _ = ([], cg)
mapAccumCg cg (x:xs) f =
  let (b, cg') = f cg x
      (bs, cg'') = mapAccumCg cg' xs f
  in (b:bs, cg'')

makeVariant :: String
makeVariant = unlines
  [ ".make_variant <- function(type, tag, fields = list()) {"
  , "  structure(c(list(`__type__` = type, `__tag__` = tag), fields),"
  , "            class = c(paste0('tl_', type, '_', tag), paste0('tl_', type), 'tl_value'))"
  , "}"
  ]
